import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:open_filex/open_filex.dart';
import 'package:uuid/uuid.dart';
import '../../../core/utils/database_helper.dart';
import '../../scanner/data/scan_model.dart';

// ─── State ────────────────────────────────────────────────────────────────────

class PdfState {
  final List<Map<String, dynamic>> pdfs;
  final bool isGenerating;
  final bool isSaving;
  final double progress;
  final String? lastPdfPath;
  final String? error;

  const PdfState({
    this.pdfs = const [],
    this.isGenerating = false,
    this.isSaving = false,
    this.progress = 0,
    this.lastPdfPath,
    this.error,
  });

  PdfState copyWith({
    List<Map<String, dynamic>>? pdfs,
    bool? isGenerating,
    bool? isSaving,
    double? progress,
    String? lastPdfPath,
    String? error,
  }) {
    return PdfState(
      pdfs:         pdfs         ?? this.pdfs,
      isGenerating: isGenerating ?? this.isGenerating,
      isSaving:     isSaving     ?? this.isSaving,
      progress:     progress     ?? this.progress,
      lastPdfPath:  lastPdfPath  ?? this.lastPdfPath,
      error:        error,
    );
  }
}

// ─── Notifier ─────────────────────────────────────────────────────────────────

class PdfNotifier extends StateNotifier<PdfState> {
  PdfNotifier() : super(const PdfState()) {
    loadPdfs();
  }

  final _db   = DatabaseHelper.instance;
  final _uuid = const Uuid();

  Future<void> loadPdfs() async {
    try {
      final pdfs = await _db.getAllPdfs();
      state = state.copyWith(pdfs: pdfs);
    } catch (_) {}
  }

  /// Generate PDF from a single scanned image + optional OCR text
  Future<String?> generateFromScan(
    ScanModel scan, {
    bool includeOcrText = false,
    PdfPageFormat format = PdfPageFormat.a4,
  }) async {
    state = state.copyWith(isGenerating: true, progress: 0.1, error: null);

    try {
      final doc = pw.Document(
        title: scan.title,
        author: 'ScanVerse AI',
      );

      state = state.copyWith(progress: 0.3);

      // Load image bytes
      final imageBytes = await File(scan.imagePath).readAsBytes();
      final pdfImage   = pw.MemoryImage(imageBytes);

      state = state.copyWith(progress: 0.5);

      // Add image page
      doc.addPage(
        pw.Page(
          pageFormat: format,
          margin: const pw.EdgeInsets.all(24),
          build: (ctx) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Container(
                padding: const pw.EdgeInsets.only(bottom: 12),
                decoration: const pw.BoxDecoration(
                  border: pw.Border(
                    bottom: pw.BorderSide(color: PdfColors.blueGrey200, width: 0.5),
                  ),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      scan.title,
                      style: pw.TextStyle(
                        fontSize: 16, fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blueGrey800,
                      ),
                    ),
                    pw.Text(
                      _formatDate(scan.createdAt),
                      style: const pw.TextStyle(
                        fontSize: 10, color: PdfColors.blueGrey400,
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 16),

              // Scanned image (fills most of page)
              pw.Expanded(
                child: pw.Center(
                  child: pw.Image(pdfImage, fit: pw.BoxFit.contain),
                ),
              ),

              // Footer
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated by ScanVerse AI',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.blueGrey300),
                textAlign: pw.TextAlign.center,
              ),
            ],
          ),
        ),
      );

      // Optional: append OCR text page
      if (includeOcrText && scan.ocrText.isNotEmpty) {
        doc.addPage(
          pw.Page(
            pageFormat: format,
            margin: const pw.EdgeInsets.all(32),
            build: (ctx) => pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Extracted Text',
                  style: pw.TextStyle(
                    fontSize: 18, fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blueGrey800,
                  ),
                ),
                pw.SizedBox(height: 16),
                pw.Text(
                  scan.ocrText,
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.blueGrey700),
                ),
              ],
            ),
          ),
        );
      }

      state = state.copyWith(progress: 0.75);

      // Save file
      final pdfBytes = await doc.save();
      final path     = await _savePdfFile(scan.title, pdfBytes);

      state = state.copyWith(progress: 0.9);

      // Save record to DB
      await _db.insertPdf({
        'id':        _uuid.v4(),
        'title':     scan.title,
        'pdfPath':   path,
        'pageCount': includeOcrText && scan.ocrText.isNotEmpty ? 2 : 1,
        'sizeBytes': pdfBytes.length,
        'createdAt': DateTime.now().toIso8601String(),
        'scanId':    scan.id,
      });
      await loadPdfs();

      state = state.copyWith(
        isGenerating: false, progress: 1.0, lastPdfPath: path,
      );
      return path;
    } catch (e) {
      state = state.copyWith(
        isGenerating: false, error: 'PDF generation failed: $e',
      );
      return null;
    }
  }

  /// Generate PDF from multiple images (multi-page)
  Future<String?> generateMultiPage(
    List<File> images,
    String title,
  ) async {
    state = state.copyWith(isGenerating: true, progress: 0, error: null);
    try {
      final doc = pw.Document(title: title, author: 'ScanVerse AI');
      final total = images.length;

      for (int i = 0; i < total; i++) {
        final bytes    = await images[i].readAsBytes();
        final pdfImage = pw.MemoryImage(bytes);

        doc.addPage(
          pw.Page(
            pageFormat: PdfPageFormat.a4,
            margin: const pw.EdgeInsets.all(16),
            build: (_) => pw.Center(
              child: pw.Image(pdfImage, fit: pw.BoxFit.contain),
            ),
          ),
        );
        state = state.copyWith(progress: (i + 1) / total);
      }

      final pdfBytes = await doc.save();
      final path     = await _savePdfFile(title, pdfBytes);

      await _db.insertPdf({
        'id':        _uuid.v4(),
        'title':     title,
        'pdfPath':   path,
        'pageCount': total,
        'sizeBytes': pdfBytes.length,
        'createdAt': DateTime.now().toIso8601String(),
        'scanId':    null,
      });
      await loadPdfs();

      state = state.copyWith(
        isGenerating: false, progress: 1.0, lastPdfPath: path,
      );
      return path;
    } catch (e) {
      state = state.copyWith(isGenerating: false, error: e.toString());
      return null;
    }
  }

  /// Share a PDF file
  Future<void> sharePdf(String pdfPath, String title) async {
    final file = XFile(pdfPath, mimeType: 'application/pdf');
    await Share.shareXFiles(
      [file],
      subject: title,
      text: 'Sharing "$title" — Scanned with ScanVerse AI',
    );
  }

  /// Open PDF with device viewer
  Future<void> openPdf(String pdfPath) async {
    await OpenFilex.open(pdfPath);
  }

  /// Print PDF
  Future<void> printPdf(String pdfPath) async {
    final bytes = await File(pdfPath).readAsBytes();
    await Printing.layoutPdf(onLayout: (_) async => bytes);
  }

  /// Delete PDF
  Future<void> deletePdf(String id, String pdfPath) async {
    final file = File(pdfPath);
    if (await file.exists()) await file.delete();
    await _db.deletePdf(id);
    await loadPdfs();
  }

  // ─── Private helpers ─────────────────────────────────────────────────────

  Future<String> _savePdfFile(String title, Uint8List bytes) async {
    final dir   = await getApplicationDocumentsDirectory();
    final pdfDir = Directory('${dir.path}/pdfs');
    if (!await pdfDir.exists()) await pdfDir.create(recursive: true);

    final safeName = title.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final path = '${pdfDir.path}/${safeName}_$timestamp.pdf';

    await File(path).writeAsBytes(bytes);
    return path;
  }

  String _formatDate(DateTime dt) {
    return '${dt.day}/${dt.month}/${dt.year}';
  }
}

// ─── Provider ────────────────────────────────────────────────────────────────

final pdfProvider = StateNotifierProvider<PdfNotifier, PdfState>(
  (_) => PdfNotifier(),
);
